/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sopadeletras;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import javax.swing.JButton;
import javax.swing.JFrame;
import sopadeletras.FondoSeleccionarModoPanel;
import sopadeletras.InterfazSopaDeLetras;

/**
 *
 * @author Dell
 */
public class InterfazSeleccionarModo extends javax.swing.JFrame {

    /**
     * Creates new form InterfazSeleccionarModo
     */
    public InterfazSeleccionarModo() {
        initComponents();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setTitle("Seleccionar Modo");
        setLocationRelativeTo(null);

        FondoSeleccionarModoPanel fondo = new FondoSeleccionarModoPanel();
        fondo.setLayout(new GridBagLayout());

        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.anchor = GridBagConstraints.CENTER;
        gbc.insets = new Insets(80, 0, 10, 0);

        // Botón: Cargar Partida Nueva
        JButton btnNueva = new JButton("CARGAR PARTIDA NUEVA");
        fondo.add(btnNueva, gbc);

        // Botón: Cargar Última Partida
        gbc.gridy = 1;
        gbc.insets = new Insets(10, 0, 0, 0);
        JButton btnUltima = new JButton("CARGAR ULTIMA PARTIDA");
        fondo.add(btnUltima, gbc);

        // Acciones
        btnNueva.addActionListener(evt -> {
            InterfazSopaDeLetras sopa = new InterfazSopaDeLetras();
            sopa.setVisible(true);
            sopa.mostrarDialogoCargarArchivo();
            dispose();
        });

        btnUltima.addActionListener(evt -> {
            InterfazSopaDeLetras sopa = new InterfazSopaDeLetras();
            sopa.setVisible(true);
            sopa.cargarUltimaPartida();
            dispose();
        });

        setContentPane(fondo);
        setSize(600, 500);
        setVisible(true);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CargarNuevaPartida = new javax.swing.JButton();
        CargarUltimaPartida = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));

        jLabel1.setText("Seleccionar Modo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, -1, -1));

        CargarNuevaPartida.setText("CARGAR PARTIDA NUEVA");
        CargarNuevaPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarNuevaPartidaActionPerformed(evt);
            }
        });
        getContentPane().add(CargarNuevaPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

        CargarUltimaPartida.setText("CARGAR ULTIMA PARTIDA");
        CargarUltimaPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarUltimaPartidaActionPerformed(evt);
            }
        });
        getContentPane().add(CargarUltimaPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CargarNuevaPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarNuevaPartidaActionPerformed
    InterfazSopaDeLetras sopa = new InterfazSopaDeLetras();
    sopa.setVisible(true);
    sopa.mostrarDialogoCargarArchivo(); // Para nueva partida
    this.dispose(); // Opcional: cerrar la ventana de selección

    }//GEN-LAST:event_CargarNuevaPartidaActionPerformed

    private void CargarUltimaPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarUltimaPartidaActionPerformed
        InterfazSopaDeLetras sopa = new InterfazSopaDeLetras();
    sopa.setVisible(true);
    sopa.cargarUltimaPartida(); // Para cargar última partida
    this.dispose(); // Opcional: cerrar la ventana de selección
    }//GEN-LAST:event_CargarUltimaPartidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazSeleccionarModo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazSeleccionarModo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazSeleccionarModo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazSeleccionarModo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazSeleccionarModo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CargarNuevaPartida;
    private javax.swing.JButton CargarUltimaPartida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
