/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sopadeletras;

import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class InterfazSopaDeLetras extends javax.swing.JFrame {
    private Diccionario diccionario;

    /**
     * Creates new form InterfazSD
     */
    public InterfazSopaDeLetras() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AreaTablero = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        AreaResultado = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        TextoPalabra = new javax.swing.JTextField();
        CargarArchivo = new javax.swing.JButton();
        BuscarPalabra = new javax.swing.JButton();
        BuscarTodasDFS = new javax.swing.JButton();
        BuscarTodasBFS = new javax.swing.JButton();
        GuardarDiccionario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, -1));

        jLabel1.setText("TABLERO DE LETRAS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        AreaTablero.setColumns(20);
        AreaTablero.setRows(5);
        jScrollPane1.setViewportView(AreaTablero);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 350, 220));

        jLabel2.setText("RESULTADO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, -1));

        AreaResultado.setColumns(20);
        AreaResultado.setRows(5);
        jScrollPane2.setViewportView(AreaResultado);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 280, 110));

        jLabel3.setText("INGRESE UNA PALABRA");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));
        getContentPane().add(TextoPalabra, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 180, 30));

        CargarArchivo.setText("CARGAR ARCHIVO");
        getContentPane().add(CargarArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, -1, -1));

        BuscarPalabra.setText("BUSCAR PALABRA");
        BuscarPalabra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarPalabraActionPerformed(evt);
            }
        });
        getContentPane().add(BuscarPalabra, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, -1, -1));

        BuscarTodasDFS.setText("BUSCAR TODAS  (DFS)");
        BuscarTodasDFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarTodasDFSActionPerformed(evt);
            }
        });
        getContentPane().add(BuscarTodasDFS, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, -1, -1));

        BuscarTodasBFS.setText("BUSCAR TODAS (BFS)");
        getContentPane().add(BuscarTodasBFS, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, -1, -1));

        GuardarDiccionario.setText("GUARDAR EN DICCIONARIO");
        GuardarDiccionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarDiccionarioActionPerformed(evt);
            }
        });
        getContentPane().add(GuardarDiccionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarPalabraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarPalabraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarPalabraActionPerformed

    private void BuscarTodasDFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarTodasDFSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarTodasDFSActionPerformed

    private void GuardarDiccionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarDiccionarioActionPerformed
    String palabra = TextoPalabra.getText().trim();
    if (palabra.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, ingrese una palabra para guardar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }

    if (diccionario == null){
        diccionario = new Diccionario();
    }
     boolean guardada = diccionario.agregarPalabra(palabra);
    if (guardada) {
        AreaResultado.append("Palabra agregada al diccionario: " + palabra + "\n");
    } else {
        AreaResultado.append("La palabra ya existe en el diccionario: " + palabra + "\n");
    }
    TextoPalabra.setText("");
    }//GEN-LAST:event_GuardarDiccionarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazSopaDeLetras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazSopaDeLetras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazSopaDeLetras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazSopaDeLetras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazSopaDeLetras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaResultado;
    private javax.swing.JTextArea AreaTablero;
    private javax.swing.JButton BuscarPalabra;
    private javax.swing.JButton BuscarTodasBFS;
    private javax.swing.JButton BuscarTodasDFS;
    private javax.swing.JButton CargarArchivo;
    private javax.swing.JButton GuardarDiccionario;
    private javax.swing.JTextField TextoPalabra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
